### ISSUE TITLE
Actively Sending Messages

### ISSUE THREAD

**Issue by derhackler** [jwarlander/hedwig_hipchat#1]
Hi,

I'm currently trying to build an agent, that is supposed to actively send messages to a chat room when certain EC2 instances are running that shouldn't run.

Replying works fine (in the responders), but how can I send a message via the agent actively? I tried:

`Hedwig.Robot.send(pid, %{text: "hello world"})`

This crashes my agent with a match error.

Best,
Benedikt

**Comment by derhackler** [comment]
Not sure if this question is related to hipchat at all, so I'll post it to the hedwig project as well.

**Comment by jwarlander** [comment]
Probably a better place! I responded there:

https://github.com/hedwig-im/hedwig/issues/34
